<!DOCTYPE html>
  
  
  
  
   <html class="no-js"> 

  <head lang="pt-br">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=10" />
    <title>Transformando Dados - Workshop P4H</title>
    <meta name="generator" content="Hugo 0.22" />

    
    <meta name="description" content="Material para Workshop P4H">
    
    <link rel="canonical" href="../manipular/">
    
    <meta name="author" content="P4H">
    

    <meta property="og:url" content="/manipular/">
    <meta property="og:title" content="Workshop P4H">
    <meta property="og:image" content="/logo_r4sc.jpg">
    <meta name="apple-mobile-web-app-title" content="Workshop P4H">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link rel="shortcut icon" type="image/x-icon" href="../images/favicon.ico">
    <link rel="icon" type="image/x-icon" href="../images/favicon.ico">
    <link rel="stylesheet" href="../stylesheets/icons.css">
    <link rel="stylesheet" href="../stylesheets/application.css">
    <link rel="stylesheet" href="../stylesheets/temporary.css">
    <link rel="stylesheet" href="../stylesheets/palettes.css">
    <link rel="stylesheet" href="../stylesheets/prism.css">

    <link rel="stylesheet" href="../stylesheets/highlight/highlight.css">

    
    
    
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Ubuntu:400,700|Ubuntu&#43;Mono">
    <style>
      body, input {
        font-family: 'Ubuntu', Helvetica, Arial, sans-serif;
      }
      pre, code {
        font-family: 'Ubuntu Mono', 'Courier New', 'Courier', monospace;
      }
    </style>

    
    <script src="../javascripts/modernizr.js"></script>

    

  </head>
  <body class="palette-primary-red palette-accent-teal">



	
	


<div class="backdrop">
	<div class="backdrop-paper"></div>
</div>

<input class="toggle" type="checkbox" id="toggle-drawer">
<input class="toggle" type="checkbox" id="toggle-search">
<label class="toggle-button overlay" for="toggle-drawer"></label>

<header class="header">
	<nav aria-label="Header">
  <div class="bar default">
    <div class="button button-menu" role="button" aria-label="Menu">
      <label class="toggle-button icon icon-menu" for="toggle-drawer">
        <span></span>
      </label>
    </div>
    <div class="stretch">
      <div class="title">
        Transformando Dados
      </div>
    </div>

    

    
    <div class="button button-github" role="button" aria-label="GitHub">
      <a href="https://github.com/p4hUSP" title="@p4hUSP on GitHub" target="_blank" class="toggle-button icon icon-github"></a>
    </div>
    
    
        
  </div>
  <div class="bar search">
    <div class="button button-close" role="button" aria-label="Close">
      <label class="toggle-button icon icon-back" for="toggle-search"></label>
    </div>
    <div class="stretch">
      <div class="field">
        <input class="query" type="text" placeholder="Search" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck>
      </div>
    </div>
    <div class="button button-reset" role="button" aria-label="Search">
      <button class="toggle-button icon icon-close" id="reset-search"></button>
    </div>
  </div>
</nav>
</header>

<main class="main">
	<div class="drawer">
		<nav aria-label="Navigation">
  <a href="../" class="project">
    <div class="banner">
      
        <div class="logo">
          <img src="../logo_r4sc.jpg">
        </div>
      
      <div class="name">
        <strong>Workshop P4H </strong>
        
          <br>
          p4hUSP/workshops_2018.2
        
      </div>
    </div>
  </a>

  <div class="scrollable">
    <div class="wrapper">
      
        <ul class="repo">
          <li class="repo-download">
            <a href="https://github.com/p4hUSP/workshops_2018.2/archive/master.zip" target="_blank" title="Download" data-action="download">
              <i class="icon icon-download"></i> Download
            </a>
          </li>
          <li class="repo-stars">
            <a href="https://github.com/p4hUSP/workshops_2018.2/stargazers" target="_blank" title="Stargazers" data-action="star">
              <i class="icon icon-star"></i> Stars
              <span class="count">&ndash;</span>
            </a>
          </li>
        </ul>
        <hr>
      

      <div class="toc">
        
        <ul>
          




<li>
  
    



<a  title="Importar" href="../importar/">
	
	Importar
</a>



  
</li>



<li>
  
    



<a class="current" title="Manipular" href="../manipular/">
	
	Manipular
</a>


<ul id="scrollspy">
</ul>


  
</li>


        </ul>
        

        
        <hr>
        <span class="section">Contatos</span>
        
        <ul>
          

          
          <li>
            <a href="https://github.com/p4hUSP" target="_blank" title="@p4hUSP no GitHub">
              @p4hUSP no GitHub
            </a>
          </li>
          

          
          <li>
            <a href="https://facebook.com/p4hUSP" target="_blank" title="@p4hUSP on Facebook">
              @p4hUSP no Facebook
            </a>
          </li>
          

          
          <li>
            <a href="https://p4husp.herokuapp.com" target="_blank" title="@p4hUSP on Slack">
              @p4hUSP on Slack
            </a>
          </li>
          

          
          <li>
            <a href="mailto:p4husp@gmail.com" title="Nosso E-Email p4husp@gmail.com">
              Envie um E-Mail
            </a>
          </li>
          
        </ul>
        
      </div>
    </div>
  </div>
</nav>

	</div>

	<article class="article">
		<div class="wrapper">
			<h1>Transformando Dados </h1>

			

<h2 id="introdução">Introdução</h2>

<p>No nosso último encontro, trabalhamos um pouco com importação de dados e <em>webscraping</em>. Uma vez que essa etapa é realizada, como proceder com o nosso banco de dados? Como transformá-lo para algo mais significado para nós? Hoje iremos entender como funciona a estruturação e a transformação de dados, de acordo com o <em>tidyverse approach</em>.</p>

<p><img src="https://raw.githubusercontent.com/p4hUSP/workshops_2018.2/master/imgs/w1_01.png" title="plot of chunk unnamed-chunk-1" alt="plot of chunk unnamed-chunk-1" style="display: block; margin: auto;" /></p>

<h2 id="estruturação">Estruturação</h2>

<blockquote>
<p>tidy datasets are all alike but every messy dataset is messy in its own way (Hadley, 2014)</p>
</blockquote>

<p>Estruturar um banco é uma tarefa <strong>essencial</strong> antes de realizar qualquer operação. Uma banco desestruturado nos impede de transformar, visualizar e até modelar as nossas variáveis! Qual padrão iremos utilizar? Trabalharemos com bancos em que as linhas contêm observações; as colunas, variáveis e as células, valores.</p>

<p><img src="https://raw.githubusercontent.com/p4hUSP/workshops_2018.2/master/imgs/tidy-1.png" title="plot of chunk unnamed-chunk-2" alt="plot of chunk unnamed-chunk-2" style="display: block; margin: auto;" /></p>

<h2 id="como-deixar-os-dados-tidy-com-o-tidyr">Como deixar os dados tidy com o <code>tidyr</code>.</h2>

<p>O pacote <code>tidyr</code> possui funções que irão nos auxiliar durante o processo de <em>estruturação</em> de um banco de dados. Ela é carregada com o comando <code>library(tidyverse)</code>.</p>

<p>Neste workshop, iremos trabalhar com o banco de dados sobre cursos <em>online</em> oferecidos pelo MIT e pela Harvard.</p>

<pre><code class="language-r"># Carrega o pacote tidyverse
library(tidyverse)

# Lê o banco de dado
banco_1 &lt;- read_csv('../data/w2/w2_01_use.csv') # Não se esqueça de alterar o caminho
</code></pre>

<p>Após carregar o nosso banco de dados, podemos dar uma &ldquo;olhada rápida&rdquo; por ele com a função <code>glimpse</code>.</p>

<pre><code class="language-r">glimpse(banco_1)
</code></pre>

<pre><code>## Observations: 290
## Variables: 25
## $ course_number                     &lt;chr&gt; &quot;6.002x&quot;, &quot;6.00x&quot;, &quot;3.091x&quot;,...
## $ launch_month                      &lt;int&gt; 9, 9, 10, 10, 10, 2, 2, 2, 2...
## $ launch_day                        &lt;int&gt; 5, 26, 9, 15, 15, 4, 5, 12, ...
## $ course_title                      &lt;chr&gt; &quot;Circuits and Electronics&quot;, ...
## $ instructors                       &lt;chr&gt; &quot;Khurram Afridi&quot;, &quot;Eric Grim...
## $ course_subject                    &lt;chr&gt; &quot;Science, Technology, Engine...
## $ year                              &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ honor_code_certificates           &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ participants                      &lt;int&gt; 36105, 62709, 16663, 129400,...
## $ audited                           &lt;int&gt; 5431, 8949, 2855, 12888, 107...
## $ certified                         &lt;int&gt; 3003, 5783, 2082, 1439, 5058...
## $ percent_played_video              &lt;dbl&gt; 83.20, 89.14, 87.49, 0.00, 7...
## $ percent_posted_forum              &lt;dbl&gt; 8.17, 14.38, 14.42, 0.00, 15...
## $ percent_grade_higher_than_zero    &lt;dbl&gt; 28.97, 39.50, 34.89, 1.11, 3...
## $ total_course_hours_per_1000       &lt;dbl&gt; 418.94, 884.04, 227.55, 220....
## $ median_hours_for_certification    &lt;dbl&gt; 64.45, 78.53, 61.28, 0.00, 7...
## $ median_age                        &lt;dbl&gt; 26, 28, 27, 28, 32, 27, 27, ...
## $ percent_male                      &lt;dbl&gt; 88.28, 83.50, 70.32, 80.02, ...
## $ percent_female                    &lt;dbl&gt; 11.72, 16.50, 29.68, 19.98, ...
## $ percent_bachelor_degree_or_higher &lt;dbl&gt; 60.68, 63.04, 58.76, 58.78, ...
## $ `2012`                            &lt;chr&gt; &quot;MITx&quot;, &quot;MITx&quot;, &quot;MITx&quot;, &quot;Har...
## $ `2013`                            &lt;chr&gt; NA, NA, NA, NA, NA, &quot;MITx&quot;, ...
## $ `2014`                            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, ...
## $ `2015`                            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, ...
## $ `2016`                            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, ...
</code></pre>

<h3 id="gather"><code>gather</code></h3>

<p>Repare que as últimas quatro colunas não são exatamente variáveis. <code>2012</code>, <code>2013</code>, <code>2014</code>, <code>2015</code> e <code>2016</code> na verdade são valores de uma outra variável, ao mesmo tempo que as células correspondentes a essas variáveis dizem respeito também a outra variável. Você saberia dizer tendo em vista apenas os valores quais são essas <strong>duas</strong> variáveis?</p>

<pre><code class="language-r">banco_2 &lt;- gather(banco_1, c(&quot;2012&quot;, &quot;2013&quot;, &quot;2014&quot;, &quot;2015&quot;, &quot;2016&quot;), key = &quot;year&quot;, value = &quot;institutions&quot;)
</code></pre>

<p>Se você está familiarizado com a notação <em>wide</em> e <em>long</em>, o que acabamos de fazer foi transformar um banco com características <em>wide</em> em um <em>long</em>. É possível ir além e afirmar que o formato <em>tidy data</em> sempre é um banco <em>long</em>.</p>

<p>Uma outra maneira de entender o que aconteceu é pensar que as linhas foram <em>derretidas</em> para formar novas variáveis.</p>

<p>Obs: Se você tiver interesse de ir mais a fundo nas diferenças de <em>wide</em> e <em>long</em>, assista este <a href="https://pt.coursera.org/lecture/designexperiments/21-long-format-and-wide-format-data-tables-dqWIT">vídeo</a></p>

<h2 id="os-principais-verbos-do-dplyr">Os principais verbos do dplyr.</h2>

<p>As funções do pacote <code>dplyr</code> podem</p>

<ol>
<li><p><code>filter</code>: filtra as linhas de um banco de dados de acordo com uma regra lógica.</p></li>

<li><p><code>mutate</code>: modifica ou cria colunas de acordo com valores fornecidos.</p></li>

<li><p><code>select</code>: seleciona ou exclui colunas de um banco de dados.</p></li>

<li><p><code>count</code>: conta os valores e uma variável.</p>

<ul>
<li>Especialmente útil para variáveis categóricas.
<br /></li>
</ul></li>

<li><p><code>group_by</code> e <code>summarise</code>: são funções normalmente utilizadas em conjunto. Elas permitem realizar operações de agregações com o banco de dados e, assim, alterar a unidade de análise.</p></li>
</ol>

<h3 id="filter">filter</h3>

<p>Vamos voltar ao nosso banco de cursos <em>online</em>. Após realizarmos uma operação a fim de tornar o nosso banco <em>long</em>, você reparou que o número de observações aumentou? Podemos verificar isso com a função <code>nrow()</code>.</p>

<pre><code class="language-r">nrow(banco_1)
</code></pre>

<pre><code>## [1] 290
</code></pre>

<pre><code class="language-r">nrow(banco_2)
</code></pre>

<pre><code>## [1] 1450
</code></pre>

<p>De 290 observações, fomos para 1450! Em alguns casos, isso não seria um problema. Porém, neste em caso em específico, houve uma criação de vários valores NA (missing) para a coluna <code>institutions</code>. Isso ocorreu porque no fundo esse banco foi transformado previamente com objetivo de produzir um exemplo para este tutorial.</p>

<p>Independentemente disso, temos que arrumar esse problema e excluir as linhas com valor NA. Como realizar isso? Antes precisamos trabalhar rapidamente com avaliações lógicas no R como também entender melhor qual a natureza desse valor de <em>missing</em> no R, o <code>NA</code>.</p>

<h3 id="valores-booleanos-e-avaliações-lógicas">Valores Booleanos e Avaliações Lógicas</h3>

<p>Valores booleanos são resultados de operações booleanas e podem ser definidos como <strong>verdadeiros</strong> ou <strong>falsos</strong>. Por convenção, trabalhamos com os termos em inglês. Portanto, <strong>TRUE</strong> ou <strong>FALSE</strong>.</p>

<p>Por operações booleanas, podemos pensar em diferentes testes que tenham <strong>necessariamente</strong> uma resposta ou verdadeira ou falsa. Por exemplo, 3 é maior do que 1? Verdadeiro! E 3 é menor do que 2? Falso! Vamos realizar essas duas operações no R.</p>

<pre><code class="language-r"># 3 é maior do que 1?

3 &gt; 1
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<pre><code class="language-r"># 3 é maior do que 1?

3 &lt; 2
</code></pre>

<pre><code>## [1] FALSE
</code></pre>

<p>Existem, obviamente, outras operações. É possível também testar a igualdade entre dois valores com <code>==</code>.</p>

<pre><code class="language-r"># 2 é igual a 2?

2 == 2
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<p>Também podemos testar se dois valores são diferentes.</p>

<pre><code class="language-r">#120 é diferente de 20?

120 != 20
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<p>Outras variações utilizadas são o maior ou igual (<code>&gt;=</code>) e o menor ou igual (<code>&lt;=</code>). Além disso, também é possível realizar essas operações com textos.</p>

<pre><code class="language-r"># &quot;harvard&quot; é igual a &quot;MIT&quot;?

&quot;harvard&quot; == &quot;MIT&quot;
</code></pre>

<pre><code>## [1] FALSE
</code></pre>

<p>Não iremos introduzir essa ideia aqui, mas caso seja de interesse também podemos utilizar as noções de maior e menor para textos. Você teria um palpite de como um texto pode ser maior do que outro?</p>

<p>Por fim, temos uma operação booleana no R para testar se um valor é <em>missing</em>. Normalmente, ao realizar a nossa coleta de dados, não conseguimos acessar determinados dados para algumas observações. De modo geral, representamos esses valores como <em>missing</em>. No R, representamos valores <em>missing</em> como NAs e para testar se um valor é NA <strong>NÃO</strong> podemos utilizar o operador <code>==</code>. Por que?</p>

<pre><code class="language-r">NA == NA
</code></pre>

<pre><code>## [1] NA
</code></pre>

<p>Ao invés de <code>==</code>, nós utilizamos a função <code>is.na()</code>.</p>

<pre><code class="language-r">is.na(NA)
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<p>Para testar se um valor <strong>não</strong> é um <em>missing</em>, precisamos adicionar um <code>!</code> antes do <code>is.na()</code>.</p>

<pre><code class="language-r">!is.na(&quot;oi&quot;)
</code></pre>

<pre><code>## [1] TRUE
</code></pre>

<pre><code class="language-r">!is.na(NA)
</code></pre>

<pre><code>## [1] FALSE
</code></pre>

<table>
<thead>
<tr>
<th>Operador</th>
<th align="center">Símbolo</th>
</tr>
</thead>

<tbody>
<tr>
<td>Igual</td>
<td align="center">==</td>
</tr>

<tr>
<td>Diferente</td>
<td align="center">!=</td>
</tr>

<tr>
<td>Maior</td>
<td align="center">&gt;</td>
</tr>

<tr>
<td>Maior ou igual</td>
<td align="center">&gt;=</td>
</tr>

<tr>
<td>Menor</td>
<td align="center">&lt;</td>
</tr>

<tr>
<td>Menor ou igual</td>
<td align="center">&lt;=</td>
</tr>

<tr>
<td>É missing</td>
<td align="center">is.na()</td>
</tr>
</tbody>
</table>

<h3 id="aplicando-operações-booleanas-em-filter">Aplicando operações booleanas em <code>filter</code>.</h3>

<p>Após essa breve exposição, talvez você tenha uma ideia de que como iremos <em>filtrar</em> as observações que <strong>não</strong> são <em>missings</em> na variável <code>institutions</code>.</p>

<pre><code class="language-r">banco_3 &lt;- filter(banco_2, !is.na(institutions))
</code></pre>

<p>Pronto, agora temos um banco com 290 observações.</p>

<h3 id="mutate">mutate</h3>

<p>Por que transformar os nossos dados? Após importar um banco para o R, antes de realizar qualquer análise, precisamos (1) garantir que as nossas variáveis estão limpas, ou seja, que todos os valores estão condizentes com o padrão esperado (2) e, às vezes, precisamos <em>recodificá-las</em> para algo com mais significado para nós.</p>

<p>Quais <em>recodificações</em> podem ser realizadas no nosso banco? Vamos utilizar novamente a função <code>glimpse</code> para ter uma ideia geral dos conteúdos das nossas variáveis.</p>

<pre><code class="language-r">glimpse(banco_3)
</code></pre>

<pre><code>## Observations: 290
## Variables: 21
## $ course_number                     &lt;chr&gt; &quot;6.002x&quot;, &quot;6.00x&quot;, &quot;3.091x&quot;,...
## $ launch_month                      &lt;int&gt; 9, 9, 10, 10, 10, 2, 2, 2, 2...
## $ launch_day                        &lt;int&gt; 5, 26, 9, 15, 15, 4, 5, 12, ...
## $ course_title                      &lt;chr&gt; &quot;Circuits and Electronics&quot;, ...
## $ instructors                       &lt;chr&gt; &quot;Khurram Afridi&quot;, &quot;Eric Grim...
## $ course_subject                    &lt;chr&gt; &quot;Science, Technology, Engine...
## $ honor_code_certificates           &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ participants                      &lt;int&gt; 36105, 62709, 16663, 129400,...
## $ audited                           &lt;int&gt; 5431, 8949, 2855, 12888, 107...
## $ certified                         &lt;int&gt; 3003, 5783, 2082, 1439, 5058...
## $ percent_played_video              &lt;dbl&gt; 83.20, 89.14, 87.49, 0.00, 7...
## $ percent_posted_forum              &lt;dbl&gt; 8.17, 14.38, 14.42, 0.00, 15...
## $ percent_grade_higher_than_zero    &lt;dbl&gt; 28.97, 39.50, 34.89, 1.11, 3...
## $ total_course_hours_per_1000       &lt;dbl&gt; 418.94, 884.04, 227.55, 220....
## $ median_hours_for_certification    &lt;dbl&gt; 64.45, 78.53, 61.28, 0.00, 7...
## $ median_age                        &lt;dbl&gt; 26, 28, 27, 28, 32, 27, 27, ...
## $ percent_male                      &lt;dbl&gt; 88.28, 83.50, 70.32, 80.02, ...
## $ percent_female                    &lt;dbl&gt; 11.72, 16.50, 29.68, 19.98, ...
## $ percent_bachelor_degree_or_higher &lt;dbl&gt; 60.68, 63.04, 58.76, 58.78, ...
## $ year                              &lt;chr&gt; &quot;2012&quot;, &quot;2012&quot;, &quot;2012&quot;, &quot;201...
## $ institutions                      &lt;chr&gt; &quot;MITx&quot;, &quot;MITx&quot;, &quot;MITx&quot;, &quot;Har...
</code></pre>

<p>Podemos, por exemplo, pensar na porcentagem de pessoas que participaram em pelo menos 50% do curso (<code>certified</code>/<code>participants</code>).</p>

<pre><code class="language-r">banco_4 &lt;- mutate(banco_3, 
                  perc_certified = (certified / participants) * 100)
</code></pre>

<p>Outra estatística relevante é a porcentagem de pessoas que compareceram em pelo menos 50% do curso (<code>audited</code>/<code>participants</code>).</p>

<pre><code class="language-r">banco_5 &lt;- mutate(banco_4, 
                  perc_audited   = (audited / participants) * 100)
</code></pre>

<p>Por fim, podemos pensar na quantidade de pessoas que ganharam certificado (<code>certified</code>) entre as que participaram em pelo menos 50% do curso (<code>audited</code>).</p>

<pre><code class="language-r">banco_6 &lt;- mutate(banco_5,
                  perc_cert_aud  = (certified / audited) * 100)
</code></pre>

<pre><code class="language-r">glimpse(banco_6)
</code></pre>

<pre><code>## Observations: 290
## Variables: 24
## $ course_number                     &lt;chr&gt; &quot;6.002x&quot;, &quot;6.00x&quot;, &quot;3.091x&quot;,...
## $ launch_month                      &lt;int&gt; 9, 9, 10, 10, 10, 2, 2, 2, 2...
## $ launch_day                        &lt;int&gt; 5, 26, 9, 15, 15, 4, 5, 12, ...
## $ course_title                      &lt;chr&gt; &quot;Circuits and Electronics&quot;, ...
## $ instructors                       &lt;chr&gt; &quot;Khurram Afridi&quot;, &quot;Eric Grim...
## $ course_subject                    &lt;chr&gt; &quot;Science, Technology, Engine...
## $ honor_code_certificates           &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ participants                      &lt;int&gt; 36105, 62709, 16663, 129400,...
## $ audited                           &lt;int&gt; 5431, 8949, 2855, 12888, 107...
## $ certified                         &lt;int&gt; 3003, 5783, 2082, 1439, 5058...
## $ percent_played_video              &lt;dbl&gt; 83.20, 89.14, 87.49, 0.00, 7...
## $ percent_posted_forum              &lt;dbl&gt; 8.17, 14.38, 14.42, 0.00, 15...
## $ percent_grade_higher_than_zero    &lt;dbl&gt; 28.97, 39.50, 34.89, 1.11, 3...
## $ total_course_hours_per_1000       &lt;dbl&gt; 418.94, 884.04, 227.55, 220....
## $ median_hours_for_certification    &lt;dbl&gt; 64.45, 78.53, 61.28, 0.00, 7...
## $ median_age                        &lt;dbl&gt; 26, 28, 27, 28, 32, 27, 27, ...
## $ percent_male                      &lt;dbl&gt; 88.28, 83.50, 70.32, 80.02, ...
## $ percent_female                    &lt;dbl&gt; 11.72, 16.50, 29.68, 19.98, ...
## $ percent_bachelor_degree_or_higher &lt;dbl&gt; 60.68, 63.04, 58.76, 58.78, ...
## $ year                              &lt;chr&gt; &quot;2012&quot;, &quot;2012&quot;, &quot;2012&quot;, &quot;201...
## $ institutions                      &lt;chr&gt; &quot;MITx&quot;, &quot;MITx&quot;, &quot;MITx&quot;, &quot;Har...
## $ perc_certified                    &lt;dbl&gt; 8.317408, 9.221962, 12.49474...
## $ perc_audited                      &lt;dbl&gt; 15.042238, 14.270679, 17.133...
## $ perc_cert_aud                     &lt;dbl&gt; 55.29368, 64.62175, 72.92469...
</code></pre>

<h3 id="verboas-para-análise-de-dados">Verboas para Análise de Dados</h3>

<p>Além de transformações com objetivo de <strong>recodificar</strong> variáveis, o <code>dplyr</code> oferece funções para análises do nosso banco.</p>

<h4 id="group-by-e-summarise"><code>group by</code> e <code>summarise</code></h4>

<p>Na última seção, criamos proporções de pessoas que completaram o curso (<code>perc_certified</code>), que participaram de pelo menos 50% das aulas (<code>perc_audited</code>) e que completaram o curso entre aqueles que participaram de pelo menos 50% das aulas (<code>perc_cert_aud</code>).</p>

<p>Para isso, precisamos utilizar duas funções: <code>group_by()</code> e <code>summarise()</code>. Essas funções, em conjunto, são poderosíssimas para análise exploratória dos nossos dados. Vamos começar pela <code>summarise()</code>.</p>

<pre><code class="language-r">summarise(banco_6, MEDIA = mean(perc_certified))
</code></pre>

<pre><code>## # A tibble: 1 x 1
##   MEDIA
##   &lt;dbl&gt;
## 1  7.78
</code></pre>

<p>No último comando, descobrimos que 7,7% é a média de certificados &ldquo;emitidos&rdquo; por curso. O cálculo dessa média foi realizado para TODAS as observações do nosso banco. Agora, como fariámos para calcular a média de certicidados emitidos por instituição? Para isso, precisamos utilizar uma função <code>group_by()</code> <strong>antes</strong>.</p>

<pre><code class="language-r">banco_6 %&gt;% 
  group_by(institutions) %&gt;% 
  summarise(CERTIFICADOS = mean(perc_certified))
</code></pre>

<pre><code>## # A tibble: 2 x 2
##   institutions CERTIFICADOS
##   &lt;chr&gt;               &lt;dbl&gt;
## 1 HarvardX            10.9 
## 2 MITx                 5.25
</code></pre>

<p>Percebe como <code>group_by()</code> e <code>summarise()</code> em conjunto são ferramentas poderosas? Podemos repetir o processo para as outras variáveis.</p>

<pre><code class="language-r">banco_6 %&gt;% 
  group_by(institutions) %&gt;% 
  summarise(PARICIPARAM_50 = mean(perc_audited))
</code></pre>

<pre><code>## # A tibble: 2 x 2
##   institutions PARICIPARAM_50
##   &lt;chr&gt;                 &lt;dbl&gt;
## 1 HarvardX               31.9
## 2 MITx                   19.3
</code></pre>

<pre><code class="language-r">banco_6 %&gt;% 
  group_by(institutions) %&gt;% 
  summarise(CERT_PART_50 = mean(perc_cert_aud))
</code></pre>

<pre><code>## # A tibble: 2 x 2
##   institutions CERT_PART_50
##   &lt;chr&gt;               &lt;dbl&gt;
## 1 HarvardX             35.2
## 2 MITx                 29.9
</code></pre>

<p>A fim de tornar o nosso trablho mais eficiente, podemos calcular mais de uma estatística dentro de <code>summarise()</code>. Logo, ao invés de calcular cada média individualmente, podemos calcular todas de uma vez.</p>

<pre><code class="language-r">banco_6 %&gt;% 
  group_by(institutions) %&gt;% 
  summarise(CERTIFICADOS   = mean(perc_certified),
            PARICIPARAM_50 = mean(perc_audited),
            CERT_PART_50   = mean(perc_cert_aud))
</code></pre>

<pre><code>## # A tibble: 2 x 4
##   institutions CERTIFICADOS PARICIPARAM_50 CERT_PART_50
##   &lt;chr&gt;               &lt;dbl&gt;          &lt;dbl&gt;        &lt;dbl&gt;
## 1 HarvardX            10.9            31.9         35.2
## 2 MITx                 5.25           19.3         29.9
</code></pre>

<p>Além de realizar mais de um cálculo por vez, também é possível adicionar mais de uma variável para o <code>group_by()</code>. Ao fazer isso, você irá trabalhar com a combinação das duas variáveis, ou seja, çaso selecionemos uma variável com <strong>3</strong> categorias e uma segunda com <strong>4</strong>, teremos no final <strong>12</strong> (3 x 4) categorias.</p>

<p>Como exemplo, vamos pensar a porcentagem de certificados emitidos por ano (<code>perc_certified</code>) e por instituição (<code>institutions</code>).</p>

<pre><code class="language-r">banco_6 %&gt;% 
  group_by(year, institutions) %&gt;% 
  summarise(CERTIFICADOS = mean(perc_certified))
</code></pre>

<pre><code>## # A tibble: 10 x 3
## # Groups:   year [?]
##    year  institutions CERTIFICADOS
##    &lt;chr&gt; &lt;chr&gt;               &lt;dbl&gt;
##  1 2012  HarvardX             5.37
##  2 2012  MITx                10.0 
##  3 2013  HarvardX             6.58
##  4 2013  MITx                 6.58
##  5 2014  HarvardX            14.9 
##  6 2014  MITx                 6.15
##  7 2015  HarvardX            12.3 
##  8 2015  MITx                 5.62
##  9 2016  HarvardX             4.57
## 10 2016  MITx                 3.20
</code></pre>

<h4 id="count"><code>count</code></h4>

<p>Com a função <code>count()</code> podemos contar as categorias presentes dentro de uma variável.</p>

<pre><code class="language-r">banco_6 %&gt;% 
  count(institutions)
</code></pre>

<pre><code>## # A tibble: 2 x 2
##   institutions     n
##   &lt;chr&gt;        &lt;int&gt;
## 1 HarvardX       129
## 2 MITx           161
</code></pre>

<pre><code class="language-r">banco_6 %&gt;% 
  count(course_subject)
</code></pre>

<pre><code>## # A tibble: 4 x 2
##   course_subject                                           n
##   &lt;chr&gt;                                                &lt;int&gt;
## 1 Computer Science                                        30
## 2 Government, Health, and Social Science                  75
## 3 Humanities, History, Design, Religion, and Education    94
## 4 Science, Technology, Engineering, and Mathematics       91
</code></pre>

<p>Também é possível, por exemplo, fornecer mais de uma variável para <code>count()</code>. Isso fará com que ela calcule a quantidade de observações presentes para as <strong>combinações</strong> de categorias.</p>

<pre><code class="language-r">banco_6 %&gt;% 
  count(institutions, course_subject)
</code></pre>

<pre><code>## # A tibble: 8 x 3
##   institutions course_subject                                           n
##   &lt;chr&gt;        &lt;chr&gt;                                                &lt;int&gt;
## 1 HarvardX     Computer Science                                         4
## 2 HarvardX     Government, Health, and Social Science                  37
## 3 HarvardX     Humanities, History, Design, Religion, and Education    80
## 4 HarvardX     Science, Technology, Engineering, and Mathematics        8
## 5 MITx         Computer Science                                        26
## 6 MITx         Government, Health, and Social Science                  38
## 7 MITx         Humanities, History, Design, Religion, and Education    14
## 8 MITx         Science, Technology, Engineering, and Mathematics       83
</code></pre>

<h2 id="exercício">Exercício</h2>

<ol>
<li><p>Investigue quais os temas de curso (<code>course_subject</code>) mais recorrentes para cada instituição (<code>institutions</code>).</p></li>

<li><p>Investigue a distribuição de gênero (<code>percent_female</code> e <code>percent_male</code>).</p>

<ul>
<li><p>2.1. Para cada instituição (<code>institutions</code>).</p></li>

<li><p>2.2. Para cada tema de curso (<code>course_subject</code>)</p></li>

<li><p>2.3. Qual seria uma possível origem da diferença da proporção de mulheres entre os cursos oferecidos pela HarvardX e a MITx? (Dica: tente pensar nos cursos oferecidos por cada instituição)</p></li>
</ul></li>

<li><p>Quais são os meses em que mais cursos são oferecidos?</p></li>
</ol>


			<aside class="copyright" role="note">
				
				&copy; 2018 Released under the MIT license &ndash;
				
				Documentation built with
				<a href="https://www.gohugo.io" target="_blank">Hugo</a>
				using the
				<a href="http://github.com/digitalcraftsman/hugo-material-docs" target="_blank">Material</a> theme.
			</aside>

			<footer class="footer">
				

<nav class="pagination" aria-label="Footer">
  <div class="previous">
  
      <a href="../manipulacao/" title="Manipulação de Dados (Data Wragling)">
        <span class="direction">
          Previous
        </span>
        <div class="page">
          <div class="button button-previous" role="button" aria-label="Previous">
            <i class="icon icon-back"></i>
          </div>
          <div class="stretch">
            <div class="title">
              Manipulação de Dados (Data Wragling)
            </div>
          </div>
        </div>
      </a>
  
  </div>

  <div class="next">
  
  </div>
</nav>





			</footer>
		</div>
	</article>

	<div class="results" role="status" aria-live="polite">
		<div class="scrollable">
			<div class="wrapper">
				<div class="meta"></div>
				<div class="list"></div>
			</div>
		</div>
	</div>
</main>

    <script>
    
      var base_url = '\/';
      var repo_id  = 'p4hUSP\/workshops_2018.2';
    
    </script>

    <script src="../javascripts/application.js"></script>
    

    <script>
      /* Add headers to scrollspy */
      var headers   = document.getElementsByTagName("h2");
      var scrollspy = document.getElementById('scrollspy');

      if(scrollspy) {
        if(headers.length > 0) {
          for(var i = 0; i < headers.length; i++) {
            var li = document.createElement("li");
            li.setAttribute("class", "anchor");

            var a  = document.createElement("a");
            a.setAttribute("href", "#" + headers[i].id);
            a.setAttribute("title", headers[i].innerHTML);
            a.innerHTML = headers[i].innerHTML;

            li.appendChild(a)
            scrollspy.appendChild(li);
          }
        } else {
          scrollspy.parentElement.removeChild(scrollspy)
        }


        /* Add permanent link next to the headers */
        var headers = document.querySelectorAll("h1, h2, h3, h4, h5, h6");

        for(var i = 0; i < headers.length; i++) {
            var a = document.createElement("a");
            a.setAttribute("class", "headerlink");
            a.setAttribute("href", "#" + headers[i].id);
            a.setAttribute("title", "Permanent link")
            a.innerHTML = "#";
            headers[i].appendChild(a);
        }
      }
    </script>

    
      <script>
        (function(i,s,o,g,r,a,m){
          i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||
          []).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;
          m.parentNode.insertBefore(a,m)
        })(window, document,
          'script', '//www.google-analytics.com/analytics.js', 'ga');
         
        ga('create', 'UA-125947516-1', 'auto');
        ga('set', 'anonymizeIp', true);
        ga('send', 'pageview');
         
        var buttons = document.querySelectorAll('a');
        Array.prototype.map.call(buttons, function(item) {
          if (item.host != document.location.host) {
            item.addEventListener('click', function() {
              var action = item.getAttribute('data-action') || 'follow';
              ga('send', 'event', 'outbound', action, item.href);
            });
          }
        });
         
        var query = document.querySelector('.query');
        query.addEventListener('blur', function() {
          if (this.value) {
            var path = document.location.pathname;
            ga('send', 'pageview', path + '?q=' + this.value);
          }
        });
      </script>
    

    <script src="../javascripts/prism.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </body>
</html>

